# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- add-azure-devops-pipeline-for-container-build-and-push-to-acr

resources:
- repo: self

variables:
- group: IoT-Platform-Api

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: getVersionNumber
    displayName: get version number
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: |
        echo "##vso[task.setvariable variable=version;isOutput=true]$(jq '.version' < package.json | sed 's/"//g')"
      name: getVersionNumber
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    variables: 
      versionNumber: $[ dependencies.getVersionNumber.outputs['getVersionNumber.version'] ]
    steps:
    - script: |
        echo $(versionNumber)
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(versionNumber)
